---
- name: Provision Redhat Enterprise Linux 8
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    # Disable SSL checking
    enable_validate_certs: no

    # vCenter Credentials
    vcenter_server: "192.168.x.x"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "password"

    # vCenter
    vcenter:
      host: 192.168.x.x
      datacenter: dc1

    # ESXi Server
    esxi:
      host: 192.168.x.x
      datastore: datastore1

    # Target Folder Environment
    folder:
      name: Development
      type: vm

    # RHEL8 - Server Specifications

    # Default Root Credentials: 
      # Username: root
      # Password: password

    # General Settings:
    rhel_base:
      is_template: yes
      name: DEV-LNX-1
      vm_state: poweredon
      template: rhel8-minimal
      guest_id: rhel8_64Guest

      # Storage Settings:
      disk:
      # Primary Disk
      - controller_number: 0
        controller_type: ide
        unit_number: 0
        size_gb: 16
        type: thin
        datastore: datastore1
        disk_mode: persistent

      # System Specifications (RAM and vCPUs)
      hardware:
        memory_mb: 1024
        num_cpus: 1
        scsi: paravirtual

      # Network Settings:
      networks:
      - name: VM Network
        connected: yes
        start_connected: yes

  tasks:
  # Create VM Templates folder
  - name: Create a folder for VM Templates
    vcenter_folder:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      datacenter_name: "{{ vcenter.datacenter }}"
      validate_certs: "{{ enable_validate_certs }}"
      folder_name: "{{ folder.name }}"
    register: templates_info

  - name: Provision and Install RHEL8
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      esxi_hostname: "{{ esxi.host }}"
      validate_certs: "{{ enable_validate_certs }}"
      datacenter: "{{ vcenter.datacenter }}"
      folder: "{{ templates_info.result.path }}"

      # General Settings:
      name: "{{ rhel_base.name }}"
      state: "{{ rhel_base.vm_state }}"
      template: "{{ rhel_base.template }}"
      guest_id: "{{ rhel_base.guest_id }}"
      datastore: "{{ esxi.datastore }}"

      disk:
      # Primary Disk
      - controller_number: "{{ rhel_base.disk.0.controller_number }}"
        controller_type: "{{ rhel_base.disk.0.controller_type }}"
        unit_number: "{{ rhel_base.disk.0.unit_number }}"
        size_gb: "{{ rhel_base.disk.0.size_gb }}"
        type: "{{ rhel_base.disk.0.type }}"
        datastore: "{{ rhel_base.disk.0.datastore }}"
        disk_mode: "{{ rhel_base.disk.0.disk_mode }}"

      # System Specifications (RAM and vCPUs)
      hardware:
        memory_mb: "{{ rhel_base.hardware.memory_mb }}"
        num_cpus: "{{ rhel_base.hardware.num_cpus }}"
        scsi: "{{ rhel_base.hardware.scsi }}"

      # Network Settings:
      networks:
      - name: "{{ rhel_base.networks.0.name }}"
        connected: "{{ rhel_base.networks.0.connected }}"
        start_connected: "{{ rhel_base.networks.0.start_connected }}"
    register: vm_info
